### ISSUE TITLE
ports-mirror restart

### ISSUE THREAD

**Issue by kallisti5** [haiku/infrastructure#20]
The ports-mirror python script has been exiting (and causing the container to restart over and over) due to a bug.

```
Fetching origin
Fetching origin
Already up to date.
updating haikuports.git/master
2018-05-23T13:58:50
	cdrtools-3.02~a09.recipe => }.tar.bz2 (http://downloads.sf.net/cdrtools/cdrtools-${portVersion/\~/}.tar.bz2)
* unable to download }.tar.bz2 - curl gave resultcode 22
2018-05-23T13:58:51
	dragonmemory-1.recipe => DragonMemory-1-source.tgz (http://cznic.dl.sourceforge.net/project/dragonmemory/DragonMemory-source.tgz)
* unable to download DragonMemory-1-source.tgz - curl gave resultcode 6
2018-05-23T13:58:51
	dragonmemory-1.recipe => DragonMemory-1-source.tgz (http://heanet.dl.sourceforge.net/project/dragonmemory/DragonMemory-source.tgz)
* unable to download DragonMemory-1-source.tgz - curl gave resultcode 22
2018-05-23T13:58:51
	abe-1.1.recipe => abe-1.1.tar.gz (http://superb-dca3.dl.sourceforge.net/project/abe/abe/abe-1.1/abe-1.1.tar.gz)
* unable to download abe-1.1.tar.gz - curl gave resultcode 6
2018-05-23T13:58:51
	cd-5.8.recipe => cd-5.8_Sources.zip (http://heanet.dl.sourceforge.net/project/canvasdraw/5.8/Docs%20and%20Sources/cd-5.8_Sources.zip)
* unable to download cd-5.8_Sources.zip - curl gave resultcode 22
2018-05-23T13:58:51
	agg-2.5.recipe => agg-2.5.tar.gz (http://gnashdev.org/tools/ltib/agg-2.5.tar.gz)
* unable to download agg-2.5.tar.gz - curl gave resultcode 22
2018-05-23T13:58:52
	aiksaurus-1.2.1.recipe => aiksaurus-1.2.1.tar.gz (http://switch.dl.sourceforge.net/project/aiksaurus/aiksaurus/1.2.1/aiksaurus-1.2.1.tar.gz)
* unable to download aiksaurus-1.2.1.tar.gz - curl gave resultcode 6
2018-05-23T13:58:52
	libpaper-1.1.24.recipe => libpaper_1.1.24.tar.gz (http://ftp.de.debian.org/debian/pool/main/libp/libpaper/libpaper_1.1.24.tar.gz)
* unable to download libpaper_1.1.24.tar.gz - curl gave resultcode 22
2018-05-23T13:58:52
	xpdf-4.00.recipe => xpdf-4.00.tar.gz (http://www.xpdfreader.com/dl/xpdf-4.00.tar.gz)
* unable to download xpdf-4.00.tar.gz - curl gave resultcode 22
2018-05-23T13:58:52
	xpdf-3.04.recipe => xpdf-3.04.tar.gz (http://mirror.ctan.org/support/xpdf/xpdf-3.04.tar.gz)
* unable to download xpdf-3.04.tar.gz - curl gave resultcode 22
Traceback (most recent call last):
  File "/usr/local/bin/update-ports-mirror", line 137, in <module>
    updateFromCheckout(gitRepoDir)
  File "/usr/local/bin/update-ports-mirror", line 87, in updateFromCheckout
    os.mkdir(targetdir)
OSError: [Errno 2] No such file or directory: '/ports-mirror/srv-www/aobook/aobook-haiku-${portVersion/_'
Fetching origin
```

**Comment by waddlesplash** [comment]
I'll look into it.
